# UQ: ['Dropout', 'Ensemble', 'Bayesian', 'SWAG', 'AER', 'PRE']
UQ: ['Bayesian', 'AER', 'PRE']
Dist : 'out' #in or out
Case: 'Navier-Stokes'
Field: 'u v p'
Model: 'FNO'
Epochs: 500
Batch Size: 5
Optimizer: 'Adam'
Learning Rate: 0.005
Scheduler Step: 100
Scheduler Gamma: 0.5
Activation: 'GeLU'
Physics Normalisation: 'No'
Normalisation Strategy: 'Min-Max'
T_in: 1    
T_out: 20
Step: 1
Width_time: 16 
Width_vars: 0  
Modes: 8
Variables: 3 
Loss Function: 'LP'
Seed: 0 
Runs: 
  Deterministic: 'wan-sensor'
  Dropout: 'dense-map'
  Ensemble: ['chill-bourbon', 'unary-player', 'magenta-flour', 'smart-flute', 'proper-rebase']
  Bayesian: 'savage-array'
  SWAG: 'nondeterministic-message'
  AER: 'wan-sensor'
  PRE: 'wan-sensor'