UQ: 'PRE'
Dist : 'in' #in or out
Case: 'Wave'
Field: 'u'
Model: 'FNO'
Epochs: 500
Batch Size: 50
Optimizer: 'Adam'
Learning Rate: 0.005
Scheduler Step: 100
Scheduler Gamma: 0.5
Activation: 'GeLU'
Physics Normalisation: 'No'
Normalisation Strategy: 'Min-Max'
T_in: 1    
T_out: 20
Step: 1
Width_time: 16 
Width_vars: 0  
Modes: 8
Variables: 1 
Loss Function: 'LP'
Seed: 0 
Runs: 
  Deterministic: 'convex-cottage'
  Dropout: 'worn-transfer'
  Ensemble: ['rude-cactus', 'heartless-eggs', 'greasy-bibliography', 'pureed-gator', 'piquant-hoop']
  Bayesian: 'hidden-program'
  SWAG: 'espressivo-horror'
  AER: 'convex-cottage'
  PRE: 'convex-cottage'